name: Ubuntu

on: [push]

jobs:
  builds:
    name: "Builds"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Compile release build
      run: |
        mkdir build-release
        cd build-release
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make

    - name: Compile debug build
      run: |
        mkdir build-debug
        cd build-debug
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make
