name: WindowsCI

on: [push]

jobs:
  Windows:
    name: "Windows"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        choco install ninja llvm
        refreshenv
    - name: Information
      run: clang -v
    - name: Compile windows-release build
      run: ninja -f windows-release.ninja
    - name: Compile windows-debug build
      run: ninja -f windows-debug.ninja
